// Code generated by go generate; DO NOT EDIT.

package anonymizer

import (
	"context"
	"sync"
)

type Component struct{}

func NewComponent() *Component {
	return &Component{}
}

func (d *Component) Start(ctx context.Context, wg *sync.WaitGroup) {
	Start(ctx, wg)
}

func (d *Component) Name() string {
	return "anonymizer"
}
